name: check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Check files
        run: yarn lint
